=== jjjesus/TrySensorConfig/TrySensorConfig/Configuration/SensorConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SensorConfig" xmlns:tns="http://www.example.org/SensorConfig" elementFormDefault="qualified">

    <element name="SensorConfigList" type="tns:SensorConfigListType"></element>
    
    <complexType name="SensorConfigListType">
    	<sequence>
    		<element name="SensorConfig" type="tns:SensorConfigType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="SensorConfigType">
    	<sequence>
    		<element name="SlotNum" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int">
    					<minInclusive value="1"></minInclusive>
    					<maxExclusive value="100"></maxExclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="Threshold" maxOccurs="unbounded"
    			minOccurs="0" type="tns:ThresholdType">
    		</element>
    		<element name="Range" type="tns:RangeType"></element>
    	</sequence>
    </complexType>


    <complexType name="ThresholdType">
    	<simpleContent>
    		<extension base="double">
    			<attribute name="Level" type="tns:LevelType"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
    
    <simpleType name="LevelType">
    	<restriction base="string">
    		<enumeration value="Lower"></enumeration>
    		<enumeration value="Upper"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="RangeType">
    	<sequence>
    		<element name="Low" type="int"></element>
    		<element name="High" type="int"></element>
    	</sequence>
    </complexType>
</schema>

=== jjjesus/TrySensorConfig/TrySensorConfig/Configuration/SensorConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<tns:SensorConfigList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/SensorConfig SensorConfig.xsd" xmlns:tns="http://www.example.org/SensorConfig">
    <tns:SensorConfig>
        <tns:SlotNum>1</tns:SlotNum>
        <tns:Name>v3_3</tns:Name>
        <tns:Threshold
            Level="Lower">10</tns:Threshold>
        <tns:Threshold
            Level="Upper">100</tns:Threshold>
    </tns:SensorConfig>
    <tns:SensorConfig>
        <tns:SlotNum>1</tns:SlotNum>
        <tns:Name>v3_3A</tns:Name>
        <tns:Threshold
            Level="Lower">10</tns:Threshold>
        <tns:Threshold
            Level="Upper">100</tns:Threshold>
    </tns:SensorConfig>
</tns:SensorConfigList>
